export const CHANGE_INPUT = "CHANGE_INPUT";

export const LOGIN_EMPLOYEE = "LOGIN_EMPLOYEE";
export const LOGIN_EMPLOYEE_SUCCESS = "LOGIN_EMPLOYEE_SUCCESS";
export const LOGIN_EMPLOYEE_FAILURE = "LOGIN_EMPLOYEE_FAILURE";

export const REGISTER_USER = "REGISTER_USER";
export const REGISTER_USER_SUCCESS = "REGISTER_USER_SUCCESS";
export const REGISTER_USER_FAILURE = "REGISTER_USER_FAILURE";
